# Generated by Django 3.1.2 on 2020-10-25 14:48
from django.db import migrations
import os
import csv


def get_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipe', 'Ingredient')

    csv_file = os.path.join('fixtures/ingredients.csv')
    data = csv.reader(open(csv_file, encoding='UTF-8'), delimiter=',')
    try:
        obj_list = [
            Ingredient(
                id=id,
                title=row[0],
                dimension='r' if row[1] == '' else row[1],
            )
            for id, row in enumerate(data)
        ]
    except (IndexError):
        return 'IndexError'

    Ingredient.objects.bulk_create(obj_list)


def get_tags(apps, schema_editor):
    Tag = apps.get_model('recipe', 'Tag')

    csv_file = os.path.join('fixtures/tags.csv')
    data = csv.reader(open(csv_file, encoding='utf-8'), delimiter=',')
    try:
        obj_list = [
            Tag(
                id=id,
                name=row[0],
                value=row[1],
                color=row[2],
            )
            for id, row in enumerate(data)
        ]
    except (IndexError):
        return 'IndexError'

    Tag.objects.bulk_create(obj_list)


def delete_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipe', 'Ingredient')
    Ingredient.objects.all().delete()


def delete_tags(apps, schema_editor):
    Tag = apps.get_model('recipe', 'Tag')
    Tag.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(get_ingredients, reverse_code=delete_ingredients),
        migrations.RunPython(get_tags, reverse_code=delete_tags),
    ]
