# Generated by Django 3.1.2 on 2020-10-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20201024_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='volue',
        ),
    ]
