# Generated by Django 3.1.2 on 2020-10-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20201024_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='volue',
            new_name='value',
        ),
    ]
