# Generated by Django 3.1.2 on 2020-10-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20201024_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followrecipe',
            old_name='follow_recipe',
            new_name='recipe',
        ),
    ]
